### ISSUE TITLE
error in the paper on chemrxiv

### ISSUE THREAD

**Issue by UnixJunkie** [reymond-group/mhfp#1]
In ECFP4, 4 is a diameter.
Hence, ECFP4 means up to two bonds away from the center atom, not four bonds away.

**Comment by daenuprobst** [comment]
Thanks, we are aware of that. Might I ask where the error occurs? On page 8 we state: 

> (according to common notation, the numbers in the fingerprint names represent
> the maximum diameter rather than the maximum radius).

Throughout the paper we refer to the radius to keep in line with the radius "notation" chosen in RDKit for the morgan fingerprint methods.

Thanks again for the comment.

**Comment by UnixJunkie** [comment]
in the abstract, I saw the error

**Comment by daenuprobst** [comment]
Thanks, we'll take this into account in the revision.

**Comment by UnixJunkie** [comment]
I'm looking forward to see this in a real journal. Then I'll read it in full. :)

**Comment by greatlse** [comment]
how to calculate ECFP4 in this paper？

**Comment by UnixJunkie** [comment]
Congrats!

https://jcheminf.biomedcentral.com/track/pdf/10.1186/s13321-018-0321-8
